server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      buffered: false
      directory: logs         # папка для логов в корне проекта
      prefix: access_log
      suffix: .log
      pattern: common       # стандартный формат лога

# настройки Spring Boot приложения
spring:
  application:
    name: distributedMessenger

  # JSON
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  # H2 база данных
  h2:
    console:
      enabled: true   # веб-консоль для просмотра БД в браузере
      path: /h2-console

  # настройки подключения к H2
  datasource:
    url: jdbc:h2:mem:weblabdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  # настройки JPA (для работы с БД через Entity)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # указываем H2
    hibernate:
      ddl-auto: update # автоматически создавать/обновлять таблицы в БД
#  datasource:
#    # DNS-имя postgres из docker-compose
#    url: jdbc:postgresql://postgres:5432/weblab_db
#    username: admin
#    password: admin
#    driverClassName: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update # Hibernate будет управлять схемой БД

file:
  upload-dir: ./uploads
jwt:
  # ключ 512+
  secret: ThisIsASecretKeyForWebLabAndItShouldBeLongEnoughAndSecureAndRandom123
  # время жизни токена в миллисекундах (1 час)
  expiration: 3600000